#!/usr/bin/env python3
"""Daily README snapshot — pulls REAL data from the GitHub API."""
import json, os, re, urllib.request
from datetime import datetime, timezone

USER = "Manashjyoti-Bora"
TOKEN = os.environ.get("GH_TOKEN", "")

def gh(url):
    req = urllib.request.Request(url, headers={
        "User-Agent": USER,
        "Accept": "application/vnd.github+json",
        **({"Authorization": f"Bearer {TOKEN}"} if TOKEN else {}),
    })
    return json.load(urllib.request.urlopen(req, timeout=30))

u = gh(f"https://api.github.com/users/{USER}")
repos = gh(f"https://api.github.com/users/{USER}/repos?per_page=100")
events = gh(f"https://api.github.com/users/{USER}/events?per_page=100")

pushes = [e for e in events if e["type"] == "PushEvent"]
commit_count = sum(len(e["payload"].get("commits", [])) for e in pushes)
last_push = pushes[0]["created_at"][:10] if pushes else "n/a"

stars = sum(r["stargazers_count"] for r in repos)
langs = {}
for r in repos:
    if r.get("language"):
        langs[r["language"]] = langs.get(r["language"], 0) + 1
top_lang = max(langs, key=langs.get) if langs else "n/a"

now = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")

W = 41  # interior width
def line(t): return "│" + t[:W].ljust(W) + "│"

block = "\n".join([
    "```text",
    "┌─ DAILY SNAPSHOT ────────────────────────┐",
    line(f" Updated ....... {now}"),
    line(f" Public repos .... {u['public_repos']}"),
    line(f" Followers ....... {u['followers']}"),
    line(f" Total stars ..... {stars}"),
    line(f" Recent commits .. {commit_count}"),
    line(f" Last push ....... {last_push}"),
    line(f" Top language .... {top_lang}"),
    "├─────────────────────────────────────────┤",
    line(" Generated by GitHub Actions — no"),
    line(" hands were involved."),
    "└─────────────────────────────────────────┘",
    "```",
])

readme = open("README.md").read()
new = re.sub(
    r"<!--AUTO-UPDATE:START-->.*?<!--AUTO-UPDATE:END-->",
    f"<!--AUTO-UPDATE:START-->\n{block}\n<!--AUTO-UPDATE:END-->",
    readme, flags=re.S)
open("README.md", "w").write(new)
print("README updated:", now)
